### ISSUE TITLE
Need to calibrate the ball management motor and feeder motor

### ISSUE THREAD

**Issue by cpostbitbuckets** [BitBucketsFRC4183/FRC2022-Rapid-React#104]
- When intaking, feeder should go in reverse faster than ball management motor is intaking
- When shooting, feeder and ball management motor should be at the same power

**Comment by cal-miller-harvard** [comment]
You should also run these motors in closed loop velocity control mode, assuming you have encoders on them. This will make the feed to the shooter more consistent and improve response time.
