### ISSUE TITLE
DrivetrainSubsystem needs an "X-wheels" method

### ISSUE THREAD

**Issue by cpostbitbuckets** [BitBucketsFRC4183/FRC2022-Rapid-React#150]
When we stop (in teleop only), we want our wheels to be in an X pattern, i.e.

```
\   /

/   \
```

This should be called in teleop anytime we are not moving the robot so we are less susceptible to pushing.

We don't want this to happen outside of teleop because we need to be able to position the robot when off field.

**Comment by forbesk** [comment]
Is this something that can be used explicitly in teleop when connected to the FMS? Something published by the drivestation? https://github.com/wpilibsuite/allwpilib/blob/d66555e42f3fb558ebe7609602fcbeee252be287/wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java

**Comment by cpostbitbuckets** [comment]
we could also do a normal "stop" when disableInit is called, so disabling the robot will snap the wheels to the correct orientation.
